name: CI
run-name: >-
  ${{ github.event_name == 'pull_request' && format('CI: PR #{0}: {1}', github.event.pull_request.number, github.event.pull_request.title) ||
      github.event_name == 'create' && format('CI: release {0}', github.ref_name) ||
      format('CI: branch push') }}
on:
  create:
    tags:
      - v*
  push:
    branches:
      - main
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      FORCE_COLOR: '1'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Restore cache
        uses: coursier/cache-action@v8.0.0
        id: coursier-cache
      - name: Setup JVM
        uses: coursier/setup-action@v2.0.2
        with:
          jvm: temurin:17
      - name: Run checks
        run: ./mill __.checkStyle + __.test + __.publishLocal
      - name: Publish artifacts
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          MILL_PGP_PASSPHRASE: ${{ secrets.MILL_PGP_PASSPHRASE }}
          MILL_PGP_SECRET_BASE64: ${{ secrets.MILL_PGP_SECRET_BASE64 }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.MILL_SONATYPE_PASSWORD }}
          MILL_SONATYPE_USERNAME: ${{ secrets.MILL_SONATYPE_USERNAME }}
        run: ./mill mill.scalalib.SonatypeCentralPublishModule/
